
task_type: train


train:
  out_dir: out/train/
  run_name: big_baseline_16
  make_unique_name: true
  log_wandb: True
  epochs: 2500
  batch_size: 16
  validate_every: 5
  checkpoint_every: 50

  optimizer:
    class_path: torch.optim.Adam
    args:
      lr: 5.0e-4

  lr_scheduler:
    class_path: torch.optim.lr_scheduler.CosineAnnealingLR
    args:
      T_max: 2500
      eta_min: 5.0e-06
      last_epoch: -1

  criterion:
    class_path: src.train.utils.loss.get_bce_with_logits_loss
    args: {}


  transform:
    class_path: src.preprocessing.transform.augmented_transform
    args:
      height: 400
      width: 400

  collate_fn:
    class_path: src.train.utils.collate_fn.get_base_collate_fn
    args: {}






