
task_type: kfold

kfold:
  k: 5
  out_dir: out/kfolds/
  run_name: resnet50_imagenet100_pretrained
  make_unique_name: true


train:
  out_dir: None # Will be set by kfolds
  log_wandb: false
  epochs: 300
  batch_size: 8
  validate_every: 5
  checkpoint_every: 50

  optimizer:
    class_path: torch.optim.Adam
    args:
      lr: 5.0e-04

  lr_scheduler:
    class_path: torch.optim.lr_scheduler.CosineAnnealingLR
    args:
      T_max: 300
      eta_min: 5.0e-06
      last_epoch: -1

  criterion:
    class_path: src.train.utils.loss.get_bce_with_logits_loss
    args: {}


  transform:
    class_path: src.preprocessing.transform.augmented_transform
    args:
      height: 400
      width: 400

  collate_fn:
    class_path: src.train.utils.collate_fn.get_base_collate_fn
    args: {}


model:
  class_path: src.model.resnet_unet.get_resnetunet
  args:
    resnet_type: resnet50
    existing_resnet_path: pretrained_resnets/resnet50-imagenet100.pth

