
random_state: 42
device: cuda

data:
  train_dir: /home/yoann/Desktop/project-2-roadseg_nsy/data/training/
  test_size: 0.2


model:
  class_path: src.model.unet.Unet
  args:
    in_channels: 3
    out_channels: 1
    dropout_prob: 0.5


test:
  transform:
    class_path: src.preprocessing.transform.default_transform
    args: {}

