
task_type: kfold

kfold:
  k: 5
  out_dir: out/kfolds/
  run_name: test_run
  make_unique_name: true


train:
  out_dir: None # Will be set by kfolds
  log_wandb: true
  epochs: 200
  batch_size: 8
  validate_every: 5
  checkpoint_every: 20

  optimizer:
    class_path: torch.optim.Adam
    args:
      lr: 0.0001

  lr_scheduler:
    class_path: torch.optim.lr_scheduler.ReduceLROnPlateau
    args:
      mode: min
      factor: 0.5
      patience: 5

  criterion:
    class_path: torch.nn.BCELoss
    args: {}


  transform:
    class_path: src.preprocessing.transform.augmented_transform
    args:
      height: 400
      width: 400

  collate_fn:
    class_path: src.train.collate_fn.get_base_collate_fn
    args: {}





